### ISSUE TITLE
total noob help

### ISSUE THREAD

**Issue by qwksilver** [pcjco/PyFuzzy-renamer#1]
i think this may be able to solve a problem of mine, but have no clue how to get it to run.  is there a windows-x64 version of this as an app/applet that i could just run, or do i need other better instructions.  Thanks!

**Comment by pcjco** [comment]
Very late answer, sorry. 
I simplified the way to use it. There is now a release available for windows 64bits (v0.2.3). Just unzip in a folder and run PyFuzzy-renamer.exe.
